name: Build Web App HTML

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip Repository Files
        run: zip -r website-app.zip . -x "*.git*"

      - name: Upload HTML App
        uses: actions/upload-artifact@v3
        with:
          name: SomitiHisab-Web-App
          path: website-app.zip
